FW_VERSION 		EQU 	1
FW_SUB_VERSION	EQU		0
HW_VERSION		EQU		1
HW_SUB_VERSION	EQU		0
MANUF_YEAR		EQU		7
MANUF_MONTH		EQU		1
SERIAL_4		EQU		0	; Unique serial number msb
SERIAL_3		EQU		0	; Unique serial number
SERIAL_2		EQU		0	; Unique serial number 
SERIAL_1		EQU		0	; Unique serial number 
SERIAL_0		EQU		0	; Unique serial number lsb

;PUBLIC FW_VERSION,FW_SUB_VERSION,HW_VERSION,HW_SUB_VERSION,MANUF_YEAR,MANUF_MONTH,SERIAL_4,SERIAL_3,SERIAL_2,SERIAL_1,SERIAL_0
;END

;?CO?IDENTITY(00080h)

